### ISSUE TITLE
file API (like s3)

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/engineering-design-adrs#21]
Rather than using shared NFS mounts (for /dor and /stacks), implement a file API (like s3).

**Comment by mjgiarlo** [comment]
What is the relationship between this and Project CHAOS? (Speaking of... what *is* Project CHAOS? Where is it documented? :thinking:)

**Comment by jcoyne** [comment]
🤷‍♂ @julianmorley ☝️ ???

**Comment by mjgiarlo** [comment]
@jcoyne I chatted with Vivian yesterday and she explained that Project CHAOS is more of a purchasing/planning effort than a technical one, so I don't think there is any relationship. Happy to be corrected by Julian, though!
